version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: gradle-wrapper
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run Tests
          command: ./gradlew clean test --rerun-tasks lintKotlin :android-sandbox:lintRelease :samples:hello-world:lintRelease :samples:hello-navigation:lintRelease :samples:hello-staterestoration:lintRelease :notes-app-bravo-android:lintRelease :notes-app:aac-navigation:lintRelease :notes-app:cicerone:lintRelease :notes-app:conductor:lintRelease :notes-app:mosby:lintRelease publishToMavenLocal
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "dependencies.gradle" }}-{{ checksum ".circleci/config.yml" }}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: gradle-wrapper
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: bravo/build/reports
          destination: bravo/reports
      - store_artifacts:
          path: bravo-android/build/reports
          destination: bravo-android/reports
      - store_artifacts:
          path: ~/.m2
          destination: m2
